# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-10 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cQuiz', '0003_movie_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
